package com.rtpa.lab3;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Integer age;
   private java.lang.Double balance;
   private java.lang.Boolean dispo = false;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Double getBalance()
   {
      return this.balance;
   }

   public void setBalance(java.lang.Double balance)
   {
      this.balance = balance;
   }

   public java.lang.Boolean getDispo()
   {
      return this.dispo;
   }

   public void setDispo(java.lang.Boolean dispo)
   {
      this.dispo = dispo;
   }

   public Person(java.lang.String name, java.lang.Integer age,
         java.lang.Double balance, java.lang.Boolean dispo)
   {
      this.name = name;
      this.age = age;
      this.balance = balance;
      this.dispo = dispo;
   }

}