package com.rtpa.lab3;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean valid = true;
   private Double amount;

   private java.lang.Double fee = 8.7;

   private java.lang.Double maxWithdrawal;

   private java.lang.Double calculateWithdrawal;

   public Request()
   {
   }

   public java.lang.Boolean getValid()
   {
      return this.valid;
   }

   public void setValid(java.lang.Boolean valid)
   {
      this.valid = valid;
   }

   public java.lang.Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }

   public java.lang.Double getFee()
   {
      return this.fee;
   }

   public void setFee(java.lang.Double fee)
   {
      this.fee = fee;
   }

   public java.lang.Double getMaxWithdrawal()
   {
      return this.maxWithdrawal;
   }

   public void setMaxWithdrawal(java.lang.Double maxWithdrawal)
   {
      this.maxWithdrawal = maxWithdrawal;
   }

   public java.lang.Double getCalculateWithdrawal()
   {
      return this.calculateWithdrawal;
   }

   public void setCalculateWithdrawal(java.lang.Double calculateWithdrawal)
   {
       double amount = calculateWithdrawal * (1 + this.fee / 100);
      this.calculateWithdrawal = amount;
   }

   public Request(java.lang.Boolean valid, java.lang.Double amount,
         java.lang.Double fee, java.lang.Double maxWithdrawal,
         java.lang.Double calculateWithdrawal)
   {
      this.valid = valid;
      this.amount = amount;
      this.fee = fee;
      this.maxWithdrawal = maxWithdrawal;
      this.calculateWithdrawal = calculateWithdrawal;
   }

}